### PR TITLE
dev(base): move mapper and business in service

### LINKED ISSUE #6: Make base entity fields protected?

### PR DESCRIPTION
**Pull request by dehghani-reza**
# Pull Request Template

## Description

[comment]: <> (Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.)

Fixes #6

## Type of change

[comment]: <> (Please delete options that are not relevant.)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Screenshots (if appropriate):

[comment]: <> (please add screenshot of changes that show before and after pull request merged.)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings
- [x] My branch is sync with development branch
- [x] I have follow conventional commit
- [x] My pull request name follow standard and have related labels

assignee: @amirfathi37 

Reviewer: @amirfathi37

### CODE REVIEW

**Review by amirfathi37 — CHANGES_REQUESTED** [review]
Firstly, tell me why did you reorder the mapper's parameters?
Secondly, I think we should extract a method for setting the entity's argument that is repeated frequently.

**Comment by dehghani-reza** [comment]
> Firstly, tell me why did you reorder the mapper's parameters? Secondly, I think we should extract a method for setting the entity's argument that is repeated frequently.

1- the order should be meaning full so I change it based on low level classes which is filled with data base to high level classes which UI gonna fill for us.
2- I can't understand what you mean in second phrase please write an example for me.

PS: please mention me so git send me a notification.
@amirfathi37

**Comment by amirfathi37** [comment]
> > Firstly, tell me why did you reorder the mapper's parameters? Secondly, I think we should extract a method for setting the entity's argument that is repeated frequently.
> 
> 1- the order should be meaning full so I change it based on low level classes which is filled with data base to high level classes which UI gonna fill for us. 2- I can't understand what you mean in second phrase please write an example for me.
> 
> PS: please mention me so git send me a notification. @amirfathi37

You repeated this section for 3 time : {
e.setState(EN_STATE.CREATED);
        e.setCreateById(dto.getUserId());//TODO get from JWT
        e.setCreateDate(LocalDateTime.now());}
        extract a method.
@dehghani-reza

**Review by amirfathi37 — APPROVED** [review]

**Comment by dehghani-reza** [comment]
> > > Firstly, tell me why did you reorder the mapper's parameters? Secondly, I think we should extract a method for setting the entity's argument that is repeated frequently.
> > 
> > 1- the order should be meaning full so I change it based on low level classes which is filled with data base to high level classes which UI gonna fill for us. 2- I can't understand what you mean in second phrase please write an example for me.
> > 
> > PS: please mention me so git send me a notification. @amirfathi37
> 
> You repeated this section for 3 time : {
> e.setState(EN_STATE.CREATED);
>         e.setCreateById(dto.getUserId());//TODO get from JWT
>         e.setCreateDate(LocalDateTime.now());}
>         extract a method.
> @dehghani-reza 

does it really bothering ?
@amirfathi37

**Comment by amirfathi37** [comment]
I merged MR.

**Pull request merged**
